FROM blockcollider/bcnode

RUN apt-get update && apt-get install -y --no-install-recommends libfile-slurp-perl && rm -rf /var/lib/apt/lists/*

# Custom entrypoint
COPY bcnode/docker-entrypoint.sh /

COPY bcnode/monkey-patch /tmp

ENTRYPOINT [ "/docker-entrypoint.sh" ]
